### ISSUE TITLE
120: MemLeak/Infinite Loop Crash

### ISSUE THREAD

**Issue by theonlypwner** [acreloaded/acr#138]
**MemLeak/Infinite Loop Crash** by `d.ruler501`
Issue 120 posted to Google Code on 2013 Apr 21 at 21:03:40

Current status: Duplicate

`d.ruler501` on 2013 Apr 21 at 21:03:40:

> <b>What steps will reproduce the problem?</b>
> 1. Play ACR
> 2. It freezes and eventually crashes
> 
> <b>What is the expected output? What do you see instead?</b>
> I expect the game to play through. Instead it freezes and quickly starts using up all available RAM. I haven't let it go the whole way and instead SIGKILL it, so I am not sure of what it will do once it fills up RAM. I assume it will crash at that point though.
> 
> <b>Please use labels and text to provide additional information.</b>
> I am not sure what is causing this or a good way to find it. I would like people to report how this is caused so we can get a good idea of where it is. Please report if you have this error on this topic http://forum.acr.victorz.ca/thread-761.html so we can compile what causes this.

`theonlypwner` on 2013 May 5 at 19:59:12:

> **Labels**: Maintainability

`theonlypwner` on 2013 Jul 30 at 00:43:55:

> Issue 138 has been merged into this issue.

`theonlypwner` on 2013 Jul 30 at 00:44:38:

> Report by blueblob11 in Issue 138:
> 
> ```
> OS=archlinux on a Sony VAIO VPCSC (on the integrated graphics card [intel])
> ACRELOADED_VERSION=20508
> SOUND=ALSA
> 
> 
> [EDITSEL] is only allowed in edit mode
> stacktrace:
> ./acreloaded_client() [0x4caf99]
> /usr/lib/libc.so.6(+0x35240) [0x7fa7555cb240]
> ./acreloaded_client() [0x467d60]
> ./acreloaded_client() [0x46d910]
> ./acreloaded_client() [0x46f6ca]
> ./acreloaded_client() [0x46f591]
> ./acreloaded_client() [0x4618b0]
> ./acreloaded_client() [0x465aa6]
> ./acreloaded_client() [0x4b2d1f]
> ./acreloaded_client() [0x454d52]
> ./acreloaded_client() [0x409d6d]
> /usr/lib/libc.so.6(__libc_start_main+0xf5) [0x7fa7555b7a15]
> ./acreloaded_client() [0x40e7f5]
> ACR error (7) ()
> OpenAL Error (A004): invalid operation, line 953
> OpenAL Error (A004): invalid operation, line 953
> OpenAL Error (A004): invalid operation, line 953
> OpenAL Error (A004): invalid operation, line 953
> OpenAL Error (A004): invalid operation, line 953
> AL lib: (EE) alc_cleanup: 1 device not closed
> ```

`theonlypwner` on 2013 Jul 30 at 00:46:49:

> Issue 95 seems to be related to this one.

`blueblob11` on 2013 Aug 18 at 17:30:30:

> I recompiled with -g and ran in gdb. This is a much better stacktrace of what I am getting, but I don't know if it is the same error as before. Still missing line numbers, but at least it can identify the actual functions.
> 
> ```
> Program received signal SIGBUS, Bus error.
> 0x0000000000467d60 in vertmodel::mesh::render(animstate&, vertmodel::anpos&, vertmodel::anpos*, float) ()
> (gdb) bt
> #0  0x0000000000467d60 in vertmodel::mesh::render(animstate&, vertmodel::anpos&, vertmodel::anpos*, float) ()
> #1  0x000000000046d910 in vertmodel::part::render(int, int, float, int, dynent*) ()
> #2  0x000000000046fbaf in md3::render(int, int, float, int, vec const&, float, float, dynent*, modelattach*, float) ()
> #3  0x00000000004643b2 in rendermodel(char const*, int, int, float, vec const&, float, float, float, int, playerent*, modelattach*, float) ()
> #4  0x00000000004d36b4 in weapon::renderhudmodel(int, bool) ()
> #5  0x0000000000454ea0 in gl_drawframe(int, int, float, float) ()
> #6  0x0000000000409d6d in main ()
> ```

`theonlypwner` on 2013 Aug 18 at 18:13:00:

> Does it happen more often when you use a specific weapon? For example, the shotgun lags on the first load for me, so does the shotgun cause it more often?
> 
> Also, for others, I told blueblob11 to use -ggdb to compile for gdb.

`blueblob11` on 2013 Aug 21 at 20:57:31:

> Sorry, don't check my mail often. I mostly use the assault rifle (M16 I think) and don't switch much, but I will try switching and see.

`blueblob11` on 2013 Aug 21 at 21:02:10:

> As a note to other people that may have problems where it freezes, if you are running in gdb, make sure to run in screen or tmux so that you can re-attach from a different tty.
> 
> ```
> tmux
> gdb ./acreloaded_client
> (gdb) r "--home=${HOME}/.acreloaded" "--init=${HOME}/.acreloaded/config/init.cfg"
> ...
> play the game
> ...
> on crash press ctrl-alt-f{1-6}
> login in the text console
> tmux a
> and then you can see your running gdb session
> ctrl-d to quit gdb
> ctrl-d to close tmux
> ctrl-d to logout of the tty
> and finally ctrl-alt-f7 to get back to your x session so you don't have to restart
> ```

`d.ruler501` on 2013 Aug 22 at 05:10:29:

> It also might be good to run in windowed mode so a crash doens't lock up your computer.

`theonlypwner` on 2013 Aug 23 at 21:35:51:

> This was covered by an earlier issue, so it should be merged into that issue.
> 
> **Labels**: -Type-Defect -Priority-Critical -Usability -Component-Engine -Performance -Maintainability
> **Merged into**: 95
> **Owner**: ---
> **Status**: Duplicate

**Comment by theonlypwner** [comment]
Issue 95 = #113

**Comment by theonlypwner** [comment]
Duplicate of #113
